// See https://aka.ms/new-console-template for more information

using Serilog;
using SQLServerToSQLServer;
using System.Drawing.Text;

string copyFrom, copyTo, directory;
Console.Title = "SQLServer to SQLServer Copy";
Console.ForegroundColor = ConsoleColor.Green;
Console.Write("Enter a SQL Server Instance to Copy From: ");
copyFrom = Console.ReadLine();

Console.Write("Enter a SQL Server Instance to Copy To: ");
copyTo = Console.ReadLine();

Console.Write("Where do you want to store files generated by this script? ");
directory = Console.ReadLine();

ProgramService.CreateFolderStructure(directory);

Log.Logger = new LoggerConfiguration()
    .WriteTo.File($"C:\\{directory}\\Logs\\SqlMigrationScript_.logs", rollingInterval: RollingInterval.Day)
    .MinimumLevel.Warning()
    .CreateLogger();

SQLService.CopySQLInstance(copyFrom, copyTo, directory);
//Added to prevent the console window from closeing
Console.ReadKey();

